notifications:
  webhooks: https://outlook.office.com/webhook/3d8e5085-15c4-4958-a6b3-2b60c8b797e4@d72758a0-a446-4e0f-a0aa-4bf95a4a10e7/TravisCI/1d6d563ba4014e34b073eab8c200d61f/8c18a7c8-be05-4398-8ba1-0d22da27a984
stages:
  - Test

jobs:
  include:
    # Unit tests
    - stage: Test
      name: "Unit tests"
      language: java

    # CWL test
    - stage: Test
      name: "Validate CWL output"
      dist: focal
      language: java
      before_install:
        - sudo apt-get -y install python3 python3-pip
        - pip3 install cwlref-runner
      script:
        # Build JAR
        - mvn package -DskipTests=true
        # Run use case
        - git clone https://github.com/Workflomics/domain-annotations
        - cd domain-annotations
        - java -jar ../target/APE-*-executable.jar WombatP_tools/config_local.json
        # Validate with CWL runner
        - cd ./WombatP_tools/CWL
        - cwltool --enable-dev --validate workflowSolution_0.cwl
