name: Release the package to Maven Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up Maven
        run: echo 'MAVEN_OPTS="-Xmx2048m -XX:MaxPermSize=512m -Djava.net.preferIPv4Stack=true"' >> $GITHUB_ENV
      
      - name: Run test
        run: gpg --list-secret-keys --keyid-format=long
        
      - name: Import GPG key
        run: echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import
        env:
          GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Deploy to OSSRH
        run: mvn clean deploy -Dmaven.test.skip=true -Dgpg.sign -Dgpg.useagent -Dsonatype.username=${{ secrets.OSSRH_USERNAME }} -Dsonatype.password=${{ secrets.OSSRH_PASSWORD }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}