name: Deploy to Maven Repository

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Deploy to OSSRH
        run: mvn clean deploy -Dmaven.test.skip=true -Dmaven.repo.local=./.m2/repository -DaltDeploymentRepository=ossrh::default::https://oss.sonatype.org/service/local/staging/deploy/maven2/ -Dsonatype.username=${{ secrets.OSSRH_USERNAME }} -Dsonatype.password=${{ secrets.OSSRH_PASSWORD }}
        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
